name: Build and Upload LaTeX PDF

on:
  push:
    tags:
      - '*'  # どんなタグでも反応する

permissions:
  contents: write

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    - name: Compile LaTeX document
      run: |
        cd manuscript/
        latexmk -pdf main.tex

    - name: Rename PDF to tag name
      run: |
        cd manuscript/
        TAG_NAME=${{ github.ref_name }}
        mv main.pdf ${TAG_NAME}.pdf

    - name: Upload PDF to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          manuscript/${{ github.ref_name }}.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
    - name: Get previous tag
      id: prev_tag
      run: |
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        echo "Previous tag is $PREV_TAG"
        echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

    - name: Get commit ID of previous tag
      if: steps.prev_tag.outputs.prev_tag != ''
      id: prev_commit
      run: |
        PREV_COMMIT=$(git rev-list -n 1 ${{ steps.prev_tag.outputs.prev_tag }})
        echo "Previous commit ID is $PREV_COMMIT"
        echo "prev_commit=$PREV_COMMIT" >> $GITHUB_OUTPUT

    - name: Run latexdiff-vc 
      if: steps.prev_tag.outputs.prev_tag != ''
      run: |
        cd manuscript/
        latexdiff-vc --git --run -c LATEX='latexmk -f' --flatten --force -r ${{ steps.prev_commit.outputs.prev_commit }}  main.tex
        ls
        
    - name: Rename diff PDF to tag name
      if: steps.prev_tag.outputs.prev_tag != ''
      run: |
        cd manuscript/
        TAG_NAME=${{ github.ref_name }}
        PREV_COMMIT=${{ steps.prev_commit.outputs.prev_commit }}
        DIFF_FILENAME=main-diff${PREV_COMMIT}.pdf 
        # ファイル存在チェック
        if [ -f ${DIFF_FILENAME} ]; then
           mv ${DIFF_FILENAME} ${TAG_NAME}-diff.pdf
        else
           echo "No diff PDF found. Skipping rename."
        fi
        
    - name: Upload diff PDF to Release
      uses: softprops/action-gh-release@v2
      if: steps.prev_tag.outputs.prev_tag != ''
      with:
        files: |
          manuscript/${{ github.ref_name }}-diff.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true  # ← ファイルがない場合に失敗しないようにする
