name: Build and Upload LaTeX PDF

on:
  push:
    tags:
      - '*'  # どんなタグでも反応する

permissions:
  contents: write

      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    - name: Compile LaTeX document
      run: |
        cd manuscript/
        latexmk -pdf main.tex

    - name: Rename PDF to tag name
      run: |
        cd manuscript/
        TAG_NAME=${{ github.ref_name }}
        mv main.pdf "${TAG_NAME}.pdf"

    - name: Get previous tag
      id: prev_tag
      run: |
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^)
        echo "Previous tag is $PREV_TAG"
        echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

    - name: Get commit ID of previous tag
      id: prev_commit
      run: |
        PREV_COMMIT=$(git rev-list -n 1 ${{ steps.prev_tag.outputs.prev_tag }})
        echo "Previous commit ID is $PREV_COMMIT"
        echo "prev_commit=$PREV_COMMIT" >> $GITHUB_OUTPUT

    - name: Run latexdiff-vc
      run: |
        cd manuscript/
        latexdiff-vc --git --pdf --flatten -r ${{ steps.prev_commit.outputs.prev_commit }} main.tex

    - name: Rename diff PDF to tag name
      run: |
        cd manuscript/
        TAG_NAME=${{ github.ref_name }}
        mv main-diff.pdf "${TAG_NAME}-diff.pdf"

    - name: Upload diff PDF to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          "manuscript/${{ github.ref_name }}.pdf"
          "manuscript/${{ github.ref_name }}-diff.pdf"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
