name: Build and Upload LaTeX PDF

on:
  push:
    tags:
      - '*'  # どんなタグでも反応する

permissions:
  contents: write

env:
  MANUSCRIPT_DIR: manuscript

jobs:
  build-main-pdf:
    runs-on: ubuntu-latest
    container: danteev/texlive:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y latexmk

    - name: Compile LaTeX document
      working-directory: ${{ env.MANUSCRIPT_DIR }}
      run: |
        latexmk -pdf main.tex

    - name: Rename PDF to tag name
      working-directory: ${{ env.MANUSCRIPT_DIR }}
      run: |
        mv main.pdf ${{ github.ref_name }}.pdf

    - name: Upload PDF to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ env.MANUSCRIPT_DIR }}/${{ github.ref_name }}.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
  build-diff-pdf:
    runs-on: ubuntu-latest
    container: danteev/texlive:latest
    needs: build-main-pdf

    steps:
    - name: Get previous tag
      id: prev_tag
      run: |
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        echo "Previous tag is $PREV_TAG"
        echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

    - name: Get commit ID of previous tag
      if: steps.prev_tag.outputs.prev_tag != ''
      id: prev_commit
      run: |
        PREV_COMMIT=$(git rev-list -n 1 ${{ steps.prev_tag.outputs.prev_tag }})
        echo "Previous commit ID is $PREV_COMMIT"
        echo "prev_commit=$PREV_COMMIT" >> $GITHUB_OUTPUT

    - name: Run latexdiff-vc 
      working-directory: ${{ env.MANUSCRIPT_DIR }}
      if: steps.prev_tag.outputs.prev_tag != ''
      run: |
        latexdiff-vc --git --run -c LATEX='latexmk -f' --flatten --force -r ${{ steps.prev_commit.outputs.prev_commit }}  main.tex
        
    - name: Rename diff PDF to tag name
      working-directory: ${{ env.MANUSCRIPT_DIR }}
      if: steps.prev_tag.outputs.prev_tag != ''
      run: |
        DIFF_PDF="main-diff${{ steps.prev_commit.outputs.prev_commit }}.pdf"
        TARGET_PDF="${{ github.ref_name }}-diff.pdf"
        if [ -f $DIFF_PDF ]; then  # check if the file exists before renaming
          mv $DIFF_PDF $TARGET_PDF
        else
          echo "No diff PDF found. Skipping rename."
        fi
        
    - name: Upload diff PDF to Release
      uses: softprops/action-gh-release@v2
      if: steps.prev_tag.outputs.prev_tag != ''
      with:
        files: |
          ${{ env.MANUSCRIPT_DIR }}/${{ github.ref_name }}-diff.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true  # ignore errors if no diff PDF is found
